name: Java

on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Set up JDK 1.11
              uses: actions/setup-java@v2
              with:
                  java-version: "11"
                  distribution: "adopt"

            - name: Build
              run: mvn --batch-mode -DskipTests package

            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  # Full git history is needed to get a proper list of changed files within `super-linter`
                  fetch-depth: 0

            - name: Lint Code Base
              uses: github/super-linter/slim@v4
              env:
                  VALIDATE_ALL_CODEBASE: true
                  DEFAULT_BRANCH: main
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  FILTER_REGEX_INCLUDE: .*src/.*
                  VALIDATE_JAVA: true
              continue-on-error: true

            - name: Test
              run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

            - name: Report
              uses: dorny/test-reporter@v1
              if: always()
              with:
                  name: Maven Tests
                  path: target/surefire-reports/*.xml
                  reporter: java-junit
                  fail-on-error: true
